### ISSUE TITLE
ERROR TypeError: Cannot read property 'isSetup' of null

### ISSUE THREAD

**Issue by botoxparty** [avatsaev/ngx-raven#2]
So following the README....

Seems like it's not initialising an instance of Raven.

Also there's an error in the README. You should be importing {RavenService} from 'ngx-raven'; not {RavenModule}

but yeah.... no idea why the it's not initialising/installing. AppModule is configured correctly...

**Comment by thomastoye** [comment]
Hitting the same error - `ravenService.raven` is not set. Downgrading to `1.0.3` fixed it for me.

**Comment by avatsaev** [comment]
I will deprecate this lib, people using Sentry with angular, read the updated official docs: https://docs.sentry.io/platforms/javascript/angular/
